[[redirects]]
  from = "/terms-and-conditions"
  to = "/terms-and-conditions.html"
  status = 200

[[redirects]]
  from = "/more"
  to = "/more.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200